---
# Based on the following starter workflows:
# - https://github.com/actions/starter-workflows/blob/main/ci/django.yml
# - https://github.com/actions/starter-workflows/blob/main/ci/python-app.yml
name: Continuous Integration (CI)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  test:
    name: Run tests

    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version-file: .python-version
          cache: pip
          cache-dependency-path: requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt
      - name: Install Google Chrome
        # TODO: Bind the GitHub Action below to a fixed version/commit ID
        uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: stable
      - name: Run tests
        run: |
          python manage.py collectstatic --no-input
          coverage run --source="." manage.py test
          coverage report --show-missing
          coverage xml
      - name: Create code coverage summary report
        uses: fmaeseele/CodeCoverageSummary@v1.3.2
        with:
          filename: coverage.xml
          badge: true
          format: markdown
          indicators: true
          output: both
      - name: Embed code coverage report in a pull request (PR)
        uses: marocchino/sticky-pull-request-comment@v2.9.4
        if: ${{ github.event.name == 'pull_request' }}
        with:
          recreate: true
          path: code-coverage-results.md
