---
# Based on the following starter workflows:
# - https://github.com/actions/starter-workflows/blob/main/ci/django.yml
# - https://github.com/actions/starter-workflows/blob/main/ci/python-app.yml
name: Continuous Integration (CI)

on: [push, pull_request]

jobs:
  test:
    name: Run tests

    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version-file: .python-version
          cache: pip
          cache-dependency-path: requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt
      - name: Install Google Chrome
        uses: abhi1693/setup-browser@v0.3.4
        with:
          browser: chrome
          version: stable
      - name: Run tests
        run: |
          coverage run --source="." manage.py test --testrunner "xmlrunner.extra.djangotestrunner.XMLTestRunner"
          coverage report --show-missing
      - name: Publish test reports
        uses: mikepenz/action-junit-report@v3
        # TODO: Restrict test report publishing only on pull request. You may
        # need to check the event type via `github` context.
        if: ${{ always() }}
        with:
          include_passed: true
          report_paths: "TEST-*.xml"
